### ISSUE TITLE
Congratulations.  Nice work.

### ISSUE THREAD

**Issue by chlangley** [JosephLalli/phasing_T2T#1]
Hello: 

This is a great project and the results look to be a wonderful resource for the community.

I don't have an issue (and since you don't have 'Discussion' or 'Feature Request') I'll ask a question here.

Do you have the switching errors distribution across each chromosome?  

Cheers,
Chuck

**Comment by JosephLalli** [comment]
Thank you for the kind words!

I'd consider that a 'feature request' - and I've added the relevant figure to the readme. If you have any additional concerns/requests, please let me know via Github, the (newly added) discussions section, or email at lalli at wisc.edu.
